import Header from "@/components/Heder/Header";
import "./globals.css";

export const metadata = {
    title: "Visit Drežnica | Rent a Room",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <body suppressHydrationWarning={true}>
                <Header />
                {children}
            </body>
        </html>
    );
}
